package by.epam.silina.medicines.model;

import static by.epam.silina.medicines.config.Constant.*;

public enum ValidationStatusEnum {
    SUCCESS_STATUS(0, OK_STATUS),
    ERROR_EMAIL_IS_EMPTY(1, EMAIL_IS_EMPTY),
    ERROR_EMAIL_IS_NOT_VALID(2, EMAIL_IS_NOT_VALID),
    ERROR_USERNAME_IS_EMPTY(3, USERNAME_IS_EMPTY),
    ERROR_USERNAME_IS_NOT_VALID(4, USERNAME_IS_NOT_VALID),
    ERROR_PASSWORD_IS_EMPTY(5, PASSWORD_IS_EMPTY),
    ERROR_PASSWORD_IS_NOT_VALID(6, PASSWORD_IS_NOT_VALID),
    ERROR_TELEPHONE_NUMBER_IS_EMPTY(7, TELEPHONE_NUMBER_IS_EMPTY),
    ERROR_TELEPHONE_NUMBER_IS_NOT_VALID(8, TELEPHONE_NUMBER_IS_NOT_VALID),
    ERROR_EMPLOYEE_POSITION_IS_EMPTY(9, EMPLOYEE_POSITION_IS_EMPTY),
    ERROR_LAST_LOGIN_IS_NULL(10, LAST_LOGIN_IS_NULL),
    ERROR_LAST_LOGIN_IS_NOT_VALID(11, LAST_LOGIN_IS_EMPTY),
    ERROR_ID_IS_NULL(12, ID_IS_NULL),
    ERROR_MEDICINE_NAME_IS_EMPTY(13, MEDICINE_NAME_IS_EMPTY),
    ERROR_COMPANY_IS_EMPTY(14, COMPANY_IS_EMPTY),
    ERROR_GROUP_IS_EMPTY(15, GROUP_IS_EMPTY),
    ERROR_VERSIONS_ARE_NULL(16, VERSIONS_ARE_NULL),
    ERROR_MEDICINE_TYPE_ENUM_IS_NULL(17, MEDICINE_TYPE_ENUM_IS_NULL),
    ERROR_DOSAGE_IS_EMPTY(18, DOSAGE_IS_EMPTY),
    ERROR_DOSAGE_IS_NOT_VALID(18, DOSAGE_IS_NOT_VALID),
    ERROR_CERTIFICATE_IS_NULL(18, CERTIFICATE_IS_NULL),
    ERROR_MEDICINE_PACKAGES_ARE_NULL(19, MEDICINE_PACKAGES_ARE_NULL),
    ERROR_CERTIFICATE_NAME_IS_EMPTY(20, CERTIFICATE_NAME_IS_EMPTY),
    ERROR_CERTIFICATE_NAME_IS_NOT_VALID(21, CERTIFICATE_NAME_IS_NOT_VALID),
    ERROR_WHO_ISSUED_IS_EMPTY(22, WHO_ISSUED_IS_EMPTY),
    ERROR_WHO_ISSUED_IS_NOT_VALID(23, WHO_ISSUED_IS_NOT_VALID),
    ERROR_REGISTRATION_NUMBER_IS_EMPTY(24, REGISTRATION_NUMBER_IS_EMPTY),
    ERROR_REGISTRATION_NUMBER_IS_NOT_VALID(25, REGISTRATION_NUMBER_IS_NOT_VALID),
    ERROR_REGISTRATION_DATE_FROM_IS_NULL(26, REGISTRATION_DATE_FROM_IS_NULL),
    ERROR_REGISTRATION_DATE_FROM_IS_NOT_VALID(27, REGISTRATION_DATE_FROM_IS_NOT_VALID),
    ERROR_REGISTRATION_DATE_TO_IS_NULL(28, REGISTRATION_DATE_TO_IS_NULL),
    ERROR_REGISTRATION_DATE_TO_IS_NOT_VALID(29, REGISTRATION_DATE_TO_IS_NOT_VALID),
    ERROR_PACKAGE_TYPE_ENUM_IS_NULL(30, PACKAGE_TYPE_ENUM_IS_NULL),
    ERROR_MEDICINE_NUMBER_IN_PACKAGE_IS_NULL(31, MEDICINE_NUMBER_IN_PACKAGE_IS_NULL),
    ERROR_MEDICINE_NUMBER_IN_PACKAGE_IS_NOT_VALID(32, MEDICINE_NUMBER_IN_PACKAGE_IS_NOT_VALID),
    ERROR_PRICE_IS_NULL(33, PRICE_IS_NULL),
    ERROR_PRICE_IS_NOT_VALID(34, PRICE_IS_NOT_VALID),
    ERROR_ID_IS_NOT_VALID(35, ID_IS_NOT_VALID),
    ERROR_IS_SEALED_IS_NOT_BOOLEAN_TYPE(36, IS_SEALED_IS_NOT_BOOLEAN_TYPE);

    int statusNumber;
    String statusDescription;

    ValidationStatusEnum(int statusNumber, String statusDescription) {
        this.statusNumber = statusNumber;
        this.statusDescription = statusDescription;
    }

    public int getStatusNumber() {
        return statusNumber;
    }

    public String getStatusDescription() {
        return statusDescription;
    }
}
